; Kiana 自定义文案（8 语种；生成器 tools/gen_nsis_langs.py 管理——勿手改）
; LanString 一律使用十进制语言 ID（2057/3076 无宏；防止错绑 2052）

; ----- en-GB (2057) -----
LangString K_ABORT 2057 "Are you sure you want to quit the Kiana Vnext Plus installer?"
LangString K_WELCOME_TITLE 2057 "Welcome to Kiana Vnext Plus"
LangString K_WELCOME_TEXT 2057 "This wizard will install Kiana Vnext Plus on your computer.$\r$\n$\r$\nPlease close all other programs before continuing.$\r$\n$\r$\nClick Next to continue."
LangString K_DIR_TOP 2057 "Choose the folder in which to install Kiana Vnext Plus."
LangString K_DIR_BOTTOM 2057 "To install in the default location, click Install. Click Browse to choose a different folder."
LangString K_FINISH_TITLE 2057 "Installation Complete"
LangString K_FINISH_TEXT 2057 "Kiana Vnext Plus has been installed.$\r$\n$\r$\nA shortcut has been placed on your desktop and in the Start menu.$\r$\n$\r$\nClick Finish to exit."
LangString K_RUN_LABEL 2057 "Launch Kiana now"
LangString K_SECTION_MAIN 2057 "Kiana Vnext Plus (required)"
LangString K_LNK_START 2057 "Kiana"
LangString K_LNK_UNINSTALL 2057 "Uninstall Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 2057 "Uninstall Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 2057 "This will remove Kiana Vnext Plus from your computer.$\r$\n$\r$\nThe uninstaller removes the application files and Start-menu shortcuts; your crawl data, cookies and settings are kept.$\r$\n$\r$\nClick Uninstall to continue."
LangString K_UNFINISH_TITLE 2057 "Uninstall Complete"
LangString K_UNFINISH_TEXT 2057 "Kiana Vnext Plus has been uninstalled.$\r$\n$\r$\nThank you for using Kiana."
LangString K_BRANDING 2057 "Kiana Labs"
LangString K_HEADER_FEATURES 2057 "Data collection engine"
LangString K_VERSION_NOTE 2057 "v2.17.1"

; ----- en-US (1033) -----
LangString K_ABORT 1033 "Are you sure you want to quit the Kiana Vnext Plus installer?"
LangString K_WELCOME_TITLE 1033 "Welcome to Kiana Vnext Plus"
LangString K_WELCOME_TEXT 1033 "This wizard will install Kiana Vnext Plus on your computer.$\r$\n$\r$\nPlease close all other programs before continuing.$\r$\n$\r$\nClick Next to continue."
LangString K_DIR_TOP 1033 "Choose the folder in which to install Kiana Vnext Plus."
LangString K_DIR_BOTTOM 1033 "To install in the default location, click Install. Click Browse to choose a different folder."
LangString K_FINISH_TITLE 1033 "Installation Complete"
LangString K_FINISH_TEXT 1033 "Kiana Vnext Plus has been installed.$\r$\n$\r$\nA shortcut has been placed on your desktop and in the Start menu.$\r$\n$\r$\nClick Finish to exit."
LangString K_RUN_LABEL 1033 "Launch Kiana now"
LangString K_SECTION_MAIN 1033 "Kiana Vnext Plus (required)"
LangString K_LNK_START 1033 "Kiana"
LangString K_LNK_UNINSTALL 1033 "Uninstall Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 1033 "Uninstall Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 1033 "This will remove Kiana Vnext Plus from your computer.$\r$\n$\r$\nThe uninstaller removes the application files and Start-menu shortcuts; your crawl data, cookies and settings are kept.$\r$\n$\r$\nClick Uninstall to continue."
LangString K_UNFINISH_TITLE 1033 "Uninstall Complete"
LangString K_UNFINISH_TEXT 1033 "Kiana Vnext Plus has been uninstalled.$\r$\n$\r$\nThank you for using Kiana."
LangString K_BRANDING 1033 "Kiana Labs"
LangString K_HEADER_FEATURES 1033 "Data collection engine"
LangString K_VERSION_NOTE 1033 "v2.17.1"

; ----- zh-CN (2052) -----
LangString K_ABORT 2052 "确定要退出 Kiana Vnext Plus 安装程序吗？"
LangString K_WELCOME_TITLE 2052 "欢迎使用 Kiana Vnext Plus"
LangString K_WELCOME_TEXT 2052 "本向导将把 Kiana Vnext Plus 安装到您的计算机。$\r$\n$\r$\n请先关闭其它程序，然后再继续。$\r$\n$\r$\n点击「下一步」继续。"
LangString K_DIR_TOP 2052 "选择 Kiana Vnext Plus 的安装位置。"
LangString K_DIR_BOTTOM 2052 "点击「安装」安装到默认位置；点击「浏览」选择其它文件夹。"
LangString K_FINISH_TITLE 2052 "安装完成"
LangString K_FINISH_TEXT 2052 "Kiana Vnext Plus 已安装完成。$\r$\n$\r$\n桌面与开始菜单已创建快捷方式。$\r$\n$\r$\n点击「完成」退出安装程序。"
LangString K_RUN_LABEL 2052 "立即启动 Kiana"
LangString K_SECTION_MAIN 2052 "Kiana Vnext Plus（必需）"
LangString K_LNK_START 2052 "Kiana"
LangString K_LNK_UNINSTALL 2052 "卸载 Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 2052 "卸载 Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 2052 "这将从您的电脑中移除 Kiana Vnext Plus。$\r$\n$\r$\n卸载程序会删除应用程序文件与开始菜单快捷方式；您的爬取数据、cookies 与设置将被保留。$\r$\n$\r$\n点击「卸载」继续。"
LangString K_UNFINISH_TITLE 2052 "卸载完成"
LangString K_UNFINISH_TEXT 2052 "Kiana Vnext Plus 已卸载。$\r$\n$\r$\n感谢使用 Kiana。"
LangString K_BRANDING 2052 "Kiana Labs"
LangString K_HEADER_FEATURES 2052 "数据采集引擎"
LangString K_VERSION_NOTE 2052 "v2.17.1"

; ----- zh-TW (1028) -----
LangString K_ABORT 1028 "確定要退出 Kiana Vnext Plus 安裝程式嗎？"
LangString K_WELCOME_TITLE 1028 "歡迎使用 Kiana Vnext Plus"
LangString K_WELCOME_TEXT 1028 "本安裝精靈將把 Kiana Vnext Plus 安裝到您的電腦。$\r$\n$\r$\n請先關閉其它程式，然後再繼續。$\r$\n$\r$\n點擊「下一步」繼續。"
LangString K_DIR_TOP 1028 "選擇 Kiana Vnext Plus 的安裝位置。"
LangString K_DIR_BOTTOM 1028 "點擊「安裝」安裝至預設位置；點擊「瀏覽」選擇其它資料夾。"
LangString K_FINISH_TITLE 1028 "安裝完成"
LangString K_FINISH_TEXT 1028 "Kiana Vnext Plus 已安裝完成。$\r$\n$\r$\n桌面與開始功能表已建立捷徑。$\r$\n$\r$\n點擊「完成」結束安裝程式。"
LangString K_RUN_LABEL 1028 "立即啟動 Kiana"
LangString K_SECTION_MAIN 1028 "Kiana Vnext Plus（必要）"
LangString K_LNK_START 1028 "Kiana"
LangString K_LNK_UNINSTALL 1028 "解除安裝 Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 1028 "解除安裝 Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 1028 "這將從您的電腦中移除 Kiana Vnext Plus。$\r$\n$\r$\n解除安裝程式會刪除應用程式檔案與開始功能表捷徑；您的爬取資料、cookies 與設定將被保留。$\r$\n$\r$\n點擊「解除安裝」繼續。"
LangString K_UNFINISH_TITLE 1028 "解除安裝完成"
LangString K_UNFINISH_TEXT 1028 "Kiana Vnext Plus 已解除安裝。$\r$\n$\r$\n感謝使用 Kiana。"
LangString K_BRANDING 1028 "Kiana Labs"
LangString K_HEADER_FEATURES 1028 "資料採集引擎"
LangString K_VERSION_NOTE 1028 "v2.17.1"

; ----- zh-HK (3076) -----
LangString K_ABORT 3076 "確定要離開 Kiana Vnext Plus 安裝程式嗎？"
LangString K_WELCOME_TITLE 3076 "歡迎使用 Kiana Vnext Plus"
LangString K_WELCOME_TEXT 3076 "本安裝精靈會將 Kiana Vnext Plus 安裝到您的電腦。$\r$\n$\r$\n請先關閉其他程式，然後再繼續。$\r$\n$\r$\n按「下一步」繼續。"
LangString K_DIR_TOP 3076 "選擇 Kiana Vnext Plus 的安裝位置。"
LangString K_DIR_BOTTOM 3076 "按「安裝」安裝至預設位置；按「瀏覽」選擇其他資料夾。"
LangString K_FINISH_TITLE 3076 "安裝完成"
LangString K_FINISH_TEXT 3076 "Kiana Vnext Plus 已安裝完成。$\r$\n$\r$\n桌面與開始功能表已建立捷徑。$\r$\n$\r$\n按「完成」結束安裝程式。"
LangString K_RUN_LABEL 3076 "立即啟動 Kiana"
LangString K_SECTION_MAIN 3076 "Kiana Vnext Plus（必要）"
LangString K_LNK_START 3076 "Kiana"
LangString K_LNK_UNINSTALL 3076 "解除安裝 Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 3076 "解除安裝 Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 3076 "這會從您的電腦移除 Kiana Vnext Plus。$\r$\n$\r$\n解除安裝程式會刪除應用程式檔案與開始功能表捷徑；您的爬取數據、cookies 與設定將獲保留。$\r$\n$\r$\n按「解除安裝」繼續。"
LangString K_UNFINISH_TITLE 3076 "解除安裝完成"
LangString K_UNFINISH_TEXT 3076 "Kiana Vnext Plus 已解除安裝。$\r$\n$\r$\n多謝使用 Kiana。"
LangString K_BRANDING 3076 "Kiana Labs"
LangString K_HEADER_FEATURES 3076 "數據採集引擎"
LangString K_VERSION_NOTE 3076 "v2.17.1"

; ----- ja-JP (1041) -----
LangString K_ABORT 1041 "Kiana Vnext Plus のインストーラーを終了しますか？"
LangString K_WELCOME_TITLE 1041 "Kiana Vnext Plus へようこそ"
LangString K_WELCOME_TEXT 1041 "このウィザードは、Kiana Vnext Plus をこのコンピューターにインストールします。$\r$\n$\r$\n続行する前に、他のアプリケーションをすべて閉じてください。$\r$\n$\r$\n「次へ」をクリックして続行してください。"
LangString K_DIR_TOP 1041 "Kiana Vnext Plus のインストール先フォルダーを選択してください。"
LangString K_DIR_BOTTOM 1041 "既定の場所にインストールする場合は「インストール」をクリックしてください。別のフォルダーを選択するには「参照」をクリックしてください。"
LangString K_FINISH_TITLE 1041 "インストールの完了"
LangString K_FINISH_TEXT 1041 "Kiana Vnext Plus のインストールが完了しました。$\r$\n$\r$\nデスクトップとスタートメニューにショートカットを作成しました。$\r$\n$\r$\n「完了」をクリックして終了してください。"
LangString K_RUN_LABEL 1041 "Kiana を今すぐ起動"
LangString K_SECTION_MAIN 1041 "Kiana Vnext Plus（必須）"
LangString K_LNK_START 1041 "Kiana"
LangString K_LNK_UNINSTALL 1041 "Kiana Vnext Plus をアンインストール"
LangString K_UNCONFIRM_TITLE 1041 "Kiana Vnext Plus のアンインストール"
LangString K_UNCONFIRM_TEXT 1041 "Kiana Vnext Plus をこのコンピューターから削除します。$\r$\n$\r$\nアンインストーラーはアプリケーションファイルとスタートメニューのショートカットを削除します。収集済みデータ・Cookie・設定は保持されます。$\r$\n$\r$\n「アンインストール」をクリックして続行してください。"
LangString K_UNFINISH_TITLE 1041 "アンインストールの完了"
LangString K_UNFINISH_TEXT 1041 "Kiana Vnext Plus はアンインストールされました。$\r$\n$\r$\nご利用ありがとうございました。"
LangString K_BRANDING 1041 "Kiana Labs"
LangString K_HEADER_FEATURES 1041 "データ収集エンジン"
LangString K_VERSION_NOTE 1041 "v2.17.1"

; ----- ko-KR (1042) -----
LangString K_ABORT 1042 "Kiana Vnext Plus 설치 프로그램을 종료하시겠습니까?"
LangString K_WELCOME_TITLE 1042 "Kiana Vnext Plus 설치 마법사"
LangString K_WELCOME_TEXT 1042 "이 마법사는 Kiana Vnext Plus를 컴퓨터에 설치합니다.$\r$\n$\r$\n계속하기 전에 다른 프로그램을 모두 닫아 주십시오.$\r$\n$\r$\n「다음」을 클릭하여 계속하십시오."
LangString K_DIR_TOP 1042 "Kiana Vnext Plus를 설치할 폴더를 선택하십시오."
LangString K_DIR_BOTTOM 1042 "기본 위치에 설치하려면 「설치」를 클릭하십시오. 다른 폴더를 선택하려면 「찾아보기」를 클릭하십시오."
LangString K_FINISH_TITLE 1042 "설치 완료"
LangString K_FINISH_TEXT 1042 "Kiana Vnext Plus 설치가 완료되었습니다.$\r$\n$\r$\n바탕 화면과 시작 메뉴에 바로 가기를 만들었습니다.$\r$\n$\r$\n「완료」를 클릭하여 종료하십시오."
LangString K_RUN_LABEL 1042 "Kiana 지금 실행"
LangString K_SECTION_MAIN 1042 "Kiana Vnext Plus (필수)"
LangString K_LNK_START 1042 "Kiana"
LangString K_LNK_UNINSTALL 1042 "Kiana Vnext Plus 제거"
LangString K_UNCONFIRM_TITLE 1042 "Kiana Vnext Plus 제거"
LangString K_UNCONFIRM_TEXT 1042 "컴퓨터에서 Kiana Vnext Plus를 제거합니다.$\r$\n$\r$\n제거 프로그램은 응용 프로그램 파일과 시작 메뉴 바로 가기를 삭제합니다. 수집한 데이터·쿠키·설정은 유지됩니다.$\r$\n$\r$\n「제거」를 클릭하여 계속하십시오."
LangString K_UNFINISH_TITLE 1042 "제거 완료"
LangString K_UNFINISH_TEXT 1042 "Kiana Vnext Plus가 제거되었습니다.$\r$\n$\r$\n이용해 주셔서 감사합니다."
LangString K_BRANDING 1042 "Kiana Labs"
LangString K_HEADER_FEATURES 1042 "데이터 수집 엔진"
LangString K_VERSION_NOTE 1042 "v2.17.1"

; ----- fr-FR (1036) -----
LangString K_ABORT 1036 "Voulez-vous vraiment quitter l'installateur de Kiana Vnext Plus ?"
LangString K_WELCOME_TITLE 1036 "Bienvenue dans Kiana Vnext Plus"
LangString K_WELCOME_TEXT 1036 "Cet assistant va installer Kiana Vnext Plus sur votre ordinateur.$\r$\n$\r$\nVeuillez fermer tous les autres programmes avant de continuer.$\r$\n$\r$\nCliquez sur « Suivant » pour continuer."
LangString K_DIR_TOP 1036 "Choisissez le dossier d'installation de Kiana Vnext Plus."
LangString K_DIR_BOTTOM 1036 "Pour installer à l'emplacement par défaut, cliquez sur « Installer ». Pour choisir un autre dossier, cliquez sur « Parcourir »."
LangString K_FINISH_TITLE 1036 "Installation terminée"
LangString K_FINISH_TEXT 1036 "Kiana Vnext Plus a été installé.$\r$\n$\r$\nUn raccourci a été créé sur le bureau et dans le menu Démarrer.$\r$\n$\r$\nCliquez sur « Terminer » pour quitter."
LangString K_RUN_LABEL 1036 "Lancer Kiana maintenant"
LangString K_SECTION_MAIN 1036 "Kiana Vnext Plus (requis)"
LangString K_LNK_START 1036 "Kiana"
LangString K_LNK_UNINSTALL 1036 "Désinstaller Kiana Vnext Plus"
LangString K_UNCONFIRM_TITLE 1036 "Désinstaller Kiana Vnext Plus"
LangString K_UNCONFIRM_TEXT 1036 "Kiana Vnext Plus sera supprimé de votre ordinateur.$\r$\n$\r$\nLe désinstallateur supprime les fichiers de l'application et les raccourcis du menu Démarrer ; vos données collectées, cookies et paramètres sont conservés.$\r$\n$\r$\nCliquez sur « Désinstaller » pour continuer."
LangString K_UNFINISH_TITLE 1036 "Désinstallation terminée"
LangString K_UNFINISH_TEXT 1036 "Kiana Vnext Plus a été désinstallé.$\r$\n$\r$\nMerci d'avoir utilisé Kiana."
LangString K_BRANDING 1036 "Kiana Labs"
LangString K_HEADER_FEATURES 1036 "Moteur de collecte de données"
LangString K_VERSION_NOTE 1036 "v2.17.1"
